# Generated by Django 5.1.1 on 2024-09-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='home.item'),
        ),
    ]
