# Generated by Django 5.1.1 on 2024-09-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pricingplan_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='product',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
