# Generated by Django 5.1.1 on 2024-09-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_pricingplan_product_pricingplan_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='product_id',
        ),
    ]
