# Generated by Django 5.1.1 on 2024-09-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_pricingplan_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='home.item'),
        ),
    ]
