# Generated by Django 5.1.1 on 2024-09-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pricingplan_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
