# Generated by Django 5.0.7 on 2024-10-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_plans', to='home.category'),
        ),
    ]
