# Generated by Django 5.0.7 on 2024-10-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pricingplan_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
