# Generated by Django 5.0.7 on 2024-10-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlanFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=255)),
                ('pricing_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_folder', to='home.pricingplan')),
            ],
        ),
    ]
