# Generated by Django 5.0.7 on 2024-10-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_pricingplanfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
