# Generated by Django 5.0.7 on 2024-10-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_pricingplan_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='avatar_url',
            new_name='amazon_link',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='customer_name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
