# Generated by Django 5.0.7 on 2024-10-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
