# Generated by Django 5.0.7 on 2024-10-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_emailsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
