# Generated by Django 5.0.7 on 2024-10-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
