# Generated by Django 5.0.7 on 2024-10-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0002_delete_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoringBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('product_url', models.CharField(max_length=255)),
            ],
        ),
    ]
